//NOME WILLIAM DA CRUZ PIRES    RA:2313707
//ENGENHARIA DE SOFTWARE    2021/2

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class CadJog extends javax.swing.JFrame {
    
    Jogador jogador;
    //BDCon t = BDCon.getGerCon();
    BDJog bdJog = BDJog.getGerJog();
    private static CadJog solo;
    
    
    private CadJog() {
        initComponents();
    }

    public static JTextField getCxNomeJog() {
        return solo.cxNomeJog;
    }

    public static JTextField getCxEstiloJog() {
        return solo.cxEstiloJog;
    }

    public static JTextField getCxGostoJog() {
        return solo.cxGostoJog;
    }

    public static JTextField getCxIdadeJog() {
        return solo.cxIdadeJog;
    }

    public static JTextField getCxQualidadeJog() {
        return solo.cxQualidadeJog;
    }

    
    
    public static CadJog getCadJog () {
        if (solo == null) {
            solo = new CadJog ();
        }
        limpar ();
        return solo;
    }
    
    public void voltaMenu () {
        this.dispose();
    }
    
    public void novoCadJog () {
        solo = new CadJog ();
        solo.setVisible (true);
        
    }
    
    public static void limpar () {
        solo.cxNomeJog.setText("");
        solo.cxIdadeJog.setText("");
        solo.cxEstiloJog.setText("");
        solo.cxGostoJog.setText("");
        solo.cxQualidadeJog.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgIni = new javax.swing.JLabel();
        rtNomeJog = new javax.swing.JLabel();
        rtIdadeJog = new javax.swing.JLabel();
        rtEstiloJog = new javax.swing.JLabel();
        rtGostoJog = new javax.swing.JLabel();
        rtQualidadeJog = new javax.swing.JLabel();
        msgInfo = new javax.swing.JLabel();
        btMenu = new javax.swing.JButton();
        btNovoCad = new javax.swing.JButton();
        cxNomeJog = new javax.swing.JTextField();
        cxIdadeJog = new javax.swing.JTextField();
        cxEstiloJog = new javax.swing.JTextField();
        cxGostoJog = new javax.swing.JTextField();
        cxQualidadeJog = new javax.swing.JTextField();
        btJogCad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        msgIni.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        msgIni.setText("CADASTRAMENTO DE JOGADOR");

        rtNomeJog.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        rtNomeJog.setText("NOME DO JOGADOR:");

        rtIdadeJog.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        rtIdadeJog.setText("IDADE DO JOGADOR:");

        rtEstiloJog.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        rtEstiloJog.setText("ESTILO DE JOGO:");

        rtGostoJog.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        rtGostoJog.setText("TIPO DE JOGO:");

        rtQualidadeJog.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        rtQualidadeJog.setText("PREFERÊNCIA EM JOGO:");

        msgInfo.setFont(new java.awt.Font("Imprint MT Shadow", 0, 12)); // NOI18N
        msgInfo.setText("*Ao clicar em <Menu> será cadastrado o jogador e esta aba fechará.");

        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        btNovoCad.setText("Novo Cadastramento");
        btNovoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoCadActionPerformed(evt);
            }
        });

        cxNomeJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeJogActionPerformed(evt);
            }
        });

        cxIdadeJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdadeJogActionPerformed(evt);
            }
        });

        cxEstiloJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxEstiloJogActionPerformed(evt);
            }
        });

        cxGostoJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxGostoJogActionPerformed(evt);
            }
        });

        cxQualidadeJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxQualidadeJogActionPerformed(evt);
            }
        });

        btJogCad.setText("Jogadores Cadastrados");
        btJogCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msgInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtNomeJog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxNomeJog))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtIdadeJog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxIdadeJog))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtGostoJog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxGostoJog))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rtEstiloJog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxEstiloJog, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(btNovoCad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btJogCad))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(rtQualidadeJog)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxQualidadeJog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(msgIni)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgIni)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtNomeJog)
                    .addComponent(cxNomeJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIdadeJog)
                    .addComponent(cxIdadeJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtEstiloJog)
                    .addComponent(cxEstiloJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtGostoJog)
                    .addComponent(cxGostoJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQualidadeJog)
                    .addComponent(cxQualidadeJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovoCad)
                    .addComponent(btJogCad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMenu)
                    .addComponent(msgInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeJogActionPerformed

    private void cxIdadeJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdadeJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdadeJogActionPerformed

    private void cxEstiloJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxEstiloJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxEstiloJogActionPerformed

    private void cxGostoJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxGostoJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxGostoJogActionPerformed

    private void cxQualidadeJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxQualidadeJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxQualidadeJogActionPerformed

    private void btNovoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoCadActionPerformed
        novoCadJog ();
    }//GEN-LAST:event_btNovoCadActionPerformed

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        cadastraJogador ();
    }//GEN-LAST:event_btMenuActionPerformed

    private void btJogCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogCadActionPerformed
        JogCad.getJogCad().setVisible(true);
    }//GEN-LAST:event_btJogCadActionPerformed

    public void cadastraJogador () {
        jogador = new Jogador ();
        
        jogador.setNome (cxNomeJog.getText().toUpperCase());
    
        try {
            jogador.setIdade (Integer.parseInt(cxIdadeJog.getText()));
            jogador.setEstilo (cxEstiloJog.getText().toUpperCase());  
            jogador.setGosto (cxGostoJog.getText().toUpperCase());
            jogador.setQualidade (cxQualidadeJog.getText().toUpperCase());
            
            jogador = bdJog.adicionaArray(jogador);
            if (jogador == null) {
                JOptionPane.showMessageDialog (null, "Já ha algum jogador com esses dados!", "Erro de Duplicidade", 0);
            } else {
                JOptionPane.showMessageDialog (null, "Jogador cadastrado com sucesso", "Cadastro Jogador", JOptionPane.INFORMATION_MESSAGE);
                voltaMenu ();
            }
        } catch (erroIdadeException idade) {
            erroIdadeException.idadeCerta(0);
        } catch (NumberFormatException i) {
            erroIdadeException.idadeCerta(1);
        } catch (erroEstiloException est) {
            est.estiloCerto();
        } catch (erroGostoException gos) {
            gos.gostoCerto();
        } catch (erroQualidadeException quali) {
            quali.qualidadeCerta();
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadJog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadJog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadJog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadJog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadJog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogCad;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btNovoCad;
    private javax.swing.JTextField cxEstiloJog;
    private javax.swing.JTextField cxGostoJog;
    private javax.swing.JTextField cxIdadeJog;
    private javax.swing.JTextField cxNomeJog;
    private javax.swing.JTextField cxQualidadeJog;
    private javax.swing.JLabel msgInfo;
    private javax.swing.JLabel msgIni;
    private javax.swing.JLabel rtEstiloJog;
    private javax.swing.JLabel rtGostoJog;
    private javax.swing.JLabel rtIdadeJog;
    private javax.swing.JLabel rtNomeJog;
    private javax.swing.JLabel rtQualidadeJog;
    // End of variables declaration//GEN-END:variables
}
